### ISSUE TITLE
zero time instant should not be marshalled as 'null'

### ISSUE THREAD

**Issue by schittler** [kubernetes/apimachinery#86] opened 2020-02-21 10:33 UTC
a meta.Time object fails to marshal to our CRDs when we use an unitialized time struct ("zero time instant" as the documentation for IsZero calls it), the cause of this seems to be a check in marshalling functions that sets the value to `[]byte("null")` as seen here:

https://github.com/kubernetes/apimachinery/blob/2373d029717c4d169463414a6127cd1d0d12680e/pkg/apis/meta/v1/time.go#L144

However, a go std time struct with `wall` and `ext` set to 0 and `loc` unset is perfectly valid.

https://golang.org/src/time/time.go#L127

The marshaller should only set `null` when the meta.Time object is nil.

**Comment by liggitt** [comment] 2020-02-21 15:17
Unfortunately, this field was originally used in places as a non-pointer, where there is no way to distinguish a zero-value from an epoch date. Changing the serialization would break backwards compatibility.

Marking as a duplicate of https://github.com/kubernetes/kubernetes/issues/86811, see discussion there

/close

**Closed by liggitt** 2020-02-21 15:17 UTC
