### ISSUE TITLE
How to use proxy with `NewUpgradeRequestRoundTripper`?

### ISSUE THREAD

**Issue by jwcesign** [kubernetes/apimachinery#161] opened 2023-08-31 16:26 UTC
As https://github.com/kubernetes/kubernetes/issues/120318 said, kubectl didn't suport proxy with `proxy-url`.

I check the code and, the reason is function `NewUpgradeRequestRoundTripper `, but how to use NewUpgradeRequestRoundTripper with `proxy-url`?

Is there any one could help me?

Thanks a lot~

**Comment by ardaguclu** [comment] 2023-09-21 07:13
This is a duplicate of https://github.com/kubernetes/kubernetes/issues/120318;
/close

**Closed** 2023-09-21 07:13 UTC
